advanote/advanote/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("authorization.urls", namespace="authorization")),
    path("today/", include("today.urls", namespace="today")),
    path("tasks/", include("tasks.urls", namespace="tasks")),
    path("notes/", include("notes.urls", namespace="notes")),
    path("projects/", include("projects.urls", namespace="projects")),
]

advanote/authorization/urls.py
import django.contrib.auth.views
import django.urls

import authorization.views
import users.views

app_name = "authorization"
urlpatterns = [
    django.urls.path(
        "",
        authorization.views.Login.as_view(),
        name="login",
    ),
    django.urls.path(
        "signup/",
        authorization.views.Signup.as_view(),
        name="signup",
    ),
    django.urls.path(
        "emailconfirm/<uidb64>/<token>",
        authorization.views.ConfirmEmail.as_view(),
        name="email_confirm",
    ),
    django.urls.path(
        "password_reset/",
        authorization.views.ResetPassword.as_view(),
        name="password_reset",
    ),
    django.urls.path(
        "password_done/",
        authorization.views.ResetPasswordDone.as_view(),
        name="password_done",
    ),
    django.urls.path(
        "password_confirm/<uidb64>/<token>",
        authorization.views.ResetPasswordConfirm.as_view(),
        name="password_confirm",
    ),
    django.urls.path(
        "password_complete/",
        authorization.views.ResetPasswordComplete.as_view(),
        name="password_complete",
    ),
    django.urls.path(
        "profile/",
        users.views.Profile.as_view(),
        name="profile",
    ),
    django.urls.path(
        "logout/",
        django.contrib.auth.views.LogoutView.as_view(
            template_name="authorization/reset_done.html",
        ),
        name="logout",
    ),
]

advanote/notes/urls.py
from django.urls import path

import notes.views


app_name = "notes"
urlpatterns = [
    path("", notes.views.Notes.as_view(), name="notes"),
    path("add_note/", notes.views.AddNote.as_view(), name="add_note"),
    path("<int:note_id>/", notes.views.EditNote.as_view(), name="edit_note"),
    path(
        "<int:note_id>/delete/",
        notes.views.DeleteNote.as_view(),
        name="delete_note",
    ),
    path("get_notes/", notes.views.GetNotes.as_view(), name="get_notes"),
]

advanote/authorization/forms.py
import django.contrib.auth.forms


class ResetPasswordForm(django.contrib.auth.forms.PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["email"].widget.attrs.update(
            {
                "class": "form-control",
                "placeholder": "Почта",
            },
        )


class SetPasswordForm(django.contrib.auth.forms.SetPasswordForm):
    def __init__(self, user, *args, **kwargs):
        super().__init__(user, *args, **kwargs)
        self.fields["new_password1"].widget.attrs.update(
            {
                "class": "form-control",
                "placeholder": "Новый пароль",
            },
        )
        self.fields["new_password2"].widget.attrs.update(
            {
                "class": "form-control",
                "placeholder": "Повторите пароль",
            },
        )


__all__ = ()

advanote/authorization/views.py
import django.contrib
from django.contrib.auth import login as auth_login
import django.contrib.auth.models
import django.contrib.auth.views
import django.contrib.messages
import django.contrib.sites.shortcuts
import django.core.mail
import django.http
import django.shortcuts
import django.template.loader
import django.urls
import django.utils.encoding
import django.utils.http
import django.views

import advanote.settings
import authorization.forms
import authorization.tokens
import users.forms
import users.models


class Signup(django.views.generic.FormView):
    template_name = "authorization/signup.html"
    form_class = users.forms.SingUpForm
    success_url = django.urls.reverse_lazy("authorization:login")

    def activate_email(self, user, email):
        subject_mail = "Подтверждение почты."
        message = django.template.loader.render_to_string(
            "authorization/activate_email.html",
            {
                "name": user.username,
                "domain": django.contrib.sites.shortcuts.get_current_site(
                    self.request,
                ).domain,
                "uid": django.utils.http.urlsafe_base64_encode(
                    django.utils.encoding.force_bytes(user.pk),
                ),
                "token": (
                    authorization.tokens.account_activation_token.make_token
                )(
                    user,
                ),
                "protocol": "https" if self.request.is_secure() else "http",
            },
        )
        django.core.mail.send_mail(
            subject_mail,
            message,
            advanote.settings.DJANGO_MAIL,
            [email],
            fail_silently=False,
        )

    def form_valid(self, form):
        user = django.contrib.auth.models.User.objects.create_user(
            password=form.cleaned_data.get("password1"),
            email=form.cleaned_data.get("email"),
            username=form.cleaned_data.get("username"),
            is_active=True,
        )
        user.save()
        profile = users.models.Profile.objects.create(user=user)
        profile.save()
        self.activate_email(user, form.cleaned_data.get("email"))
        django.contrib.messages.success(
            self.request,
            "Спасибо за регистрацию. Вся необходимая"
            " информация выслана на ваш e-mail. Если письмо"
            " от нас не пришло, то проверьте его в папке спама.",
        )
        return super().form_valid(form)


class Login(django.views.generic.FormView):
    template_name = "authorization/login.html"
    form_class = users.forms.LogInForm
    success_url = django.urls.reverse_lazy("today:today")

    def form_valid(self, form):
        user = form.get_user()
        auth_login(self.request, user)
        return super().form_valid(form)

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()
        return form_class(self.request, **self.get_form_kwargs())


class ConfirmEmail(django.views.generic.View):
    def get(self, request, *args, **kwargs):
        user, valid = authorization.tokens.account_activation_token.get_user(
            kwargs["uidb64"],
            kwargs["token"],
        )

        if valid and user.profile.email_confirm:
            return django.shortcuts.redirect("today:today")

        if valid:
            user.profile.email_confirm = True
            user.profile.save()
            django.contrib.messages.success(
                request,
                "Спасибо за подтверждение почты!"
                " Теперь можете войти в аккаунт!",
            )
            return django.shortcuts.redirect("authorization:login")

        django.contrib.messages.error(
            request,
            "Ссылка активации не действительна!",
        )
        return django.shortcuts.redirect("authorization:login")


class ResetPassword(django.contrib.auth.views.PasswordResetView):
    template_name = "authorization/reset_password.html"
    email_template_name = "authorization/password_reset_email.html"
    subject_template_name = "authorization/password_reset_email_subject.txt"
    success_url = django.urls.reverse_lazy("authorization:password_done")
    token_generator = authorization.tokens.account_activation_token
    form_class = authorization.forms.ResetPasswordForm


class ResetPasswordDone(django.contrib.auth.views.PasswordResetDoneView):
    template_name = "authorization/reset_done.html"


class ResetPasswordConfirm(django.contrib.auth.views.PasswordResetConfirmView):
    success_url = django.urls.reverse_lazy("authorization:password_complete")
    token_generator = authorization.tokens.account_activation_token
    template_name = "authorization/reset_confirm.html"
    form_class = authorization.forms.SetPasswordForm


class ResetPasswordComplete(
    django.contrib.auth.views.PasswordResetCompleteView,
):
    template_name = "authorization/reset_done.html"


__all__ = ()

advanote/templates/authorization/account_login.html
{% autoescape off %}
Привет {{ name }},

Кто - то вошёл в ваш аккаунт, если это были не вы, перейдите по ссылке и смените пароль:
{{ protocol }}://{{ domain }}{% url 'authorization:password_confirm' uidb64=uid token=token %}
{% endautoescape %}

advanote/templates/authorization/activate_email.html
{% autoescape off %}
Привет {{ name }},

Пожалуйста, нажмите на ссылку, чтобы подтвердить почту:

{{ protocol }}://{{ domain }}{% url 'authorization:email_confirm' uidb64=uid token=token %}
{% endautoescape %}

advanote/templates/authorization/login.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Advanote{% endblock %}</title>
    <link rel="icon" type="image/png" href="{% static 'img/logo.png' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/authorization.css' %}" rel="stylesheet">
</head>
<body>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<div class="background-image" style="background-image: url('{% static "img/background.jpeg" %}');">
    <div class="container">
        <form class="login-form" method="post" action="{% url 'authorization:login' %}">
            {% csrf_token %}
            <img src="{% static 'img/logo.png' %}" alt="Логотип" class="logo">
            <h2 class="text-center" style="margin-bottom: 50px;">Войти</h2>

                {% if form.errors %}
            <p class="text-center" style="font-size: 15px; color: #CD2A08;">Неверный логин или пароль</p>
                {% endif %}

            <div class="form-group">
                {{ form.username }}
            </div>
            <div class="form-group">
                {{ form.password }}
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-block button">Войти</button>
            </div>
        <div class="text-center">
            <a href="{% url 'authorization:password_reset' %}">Забыли пароль?</a>
            <p>Нет аккаунта? <a href="{% url 'authorization:signup' %}">Зарегистрируйтесь</a></p>
        </div>
        </form>
    </div>
</body>

advanote/templates/authorization/password_reset_email.html
{% autoescape off %}
Привет {{ name }},

Вы запросили восстановления пароля, перейдите по ссылке, чтобы восстановить:
{{ protocol }}://{{ domain }}{% url 'authorization:password_confirm' uidb64=uid token=token %}
{% endautoescape %}

advanote/templates/authorization/reset_confirm.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Advanote{% endblock %}</title>
    <link rel="icon" type="image/png" href="{% static 'img/logo.png' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/authorization.css' %}" rel="stylesheet">
</head>
<body>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<div class="background-image" style="background-image: url('{% static "img/background.jpeg" %}');">
    <div class="container">
        <form class="reset-form" method="post">
            {% csrf_token %}
            <img src="{% static 'img/logo.png' %}" alt="Логотип" class="logo">
            <h2 class="text-center" style="margin-bottom: 50px;">Изменение пароля</h2>
                {% if form.errors %}
            <p class="text-center" style="font-size: 15px; color: #CD2A08;">Неверный логин или пароль</p>
                {% endif %}

            <div class="form-group">
                {{ form.new_password1 }}
            </div>
            <div class="form-group">
                {{ form.new_password2 }}
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-block button">Изменить</button>
            </div>
        </form>
    </div>
</body>

advanote/templates/authorization/reset_done.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Advanote{% endblock %}</title>
    <link rel="icon" type="image/png" href="{% static 'img/logo.png' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/authorization.css' %}" rel="stylesheet">
</head>
<body>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
{% with request.resolver_match.view_name as view_name %}
<div class="background-image" style="background-image: url('{% static "img/background.jpeg" %}');">
    <div class="container">
        <h3 class="container-done">
            {% if view_name  == 'authorization:password_done' %} Мы отправили инструкцию по восстановлению пароля на вашу почту. Если письма нет, то проверьте спам. {% endif %}
            {% if view_name  == 'authorization:password_complete' %} Пароль успешно изменен. {% endif %}
            {% if view_name  == 'authorization:logout' %} Вы вышли из аккаунта! {% endif %}
        </h3>
    </div>
</body>
{% endwith %}

advanote/templates/authorization/reset_password.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Advanote{% endblock %}</title>
    <link rel="icon" type="image/png" href="{% static 'img/logo.png' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/authorization.css' %}" rel="stylesheet">
</head>
<body>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<div class="background-image" style="background-image: url('{% static "img/background.jpeg" %}');">
    <div class="container">
        <form class="reset-form" method="post" action="{% url 'authorization:password_reset' %}">
            {% csrf_token %}
            <img src="{% static 'img/logo.png' %}" alt="Логотип" class="logo">
            <h2 class="text-center" style="margin-bottom: 50px;">Восстановление пароля</h2>
                {% if form.errors %}
            <p class="text-center" style="font-size: 15px; color: #CD2A08;">Неверный логин или пароль</p>
                {% endif %}

            <div class="form-group">
                {{ form.email }}
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-block button">Восстановить</button>
            </div>
        </form>
    </div>
</body>

advanote/templates/authorization/signup.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Advanote{% endblock %}</title>
    <link rel="icon" type="image/png" href="{% static 'img/logo.png' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/authorization.css' %}" rel="stylesheet">
</head>
<body>
<div class="background-image" style="background-image: url('{% static "img/background.jpeg" %}');">
    <div class="container">
        <form class="signup-form" method="post" action="{% url 'authorization:signup' %}">
            {% csrf_token %}
            <img src="{% static 'img/logo.png' %}" alt="Логотип" class="logo">
            <h2 class="text-center" style="margin-bottom: 50px;">Зарегистрироваться</h2>
            <div class="form-group">
                {{ form.username }}
            </div>
            <div class="form-group">
                {{ form.email }}
            </div>
            <div class="form-group">
                {{ form.password1 }}
            </div>
            <div class="form-group">
                {{ form.password2 }}
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-block button">Зарегистрироваться</button>
            </div>
        <div class="text-center">
            <p>Уже есть аккаунт? <a href="{% url 'authorization:login' %}">Войти</a></p>
        </div>
        </form>
    </div>
</div>
</body>