advanote/advanote/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("authorization.urls", namespace="authorization")),
    path("today/", include("today.urls", namespace="today")),
    path("tasks/", include("tasks.urls", namespace="tasks")),
    path("notes/", include("notes.urls", namespace="notes")),
    path("projects/", include("projects.urls", namespace="projects")),
]

advanote/notes/urls.py
from django.urls import path

import notes.views


app_name = "notes"
urlpatterns = [
    path("", notes.views.Notes.as_view(), name="notes"),
    path("add_note/", notes.views.AddNote.as_view(), name="add_note"),
    path("<int:note_id>/", notes.views.EditNote.as_view(), name="edit_note"),
    path(
        "<int:note_id>/delete/",
        notes.views.DeleteNote.as_view(),
        name="delete_note",
    ),
    path("get_notes/", notes.views.GetNotes.as_view(), name="get_notes"),
]

advanote/notes/models.py
import django.db.models

import core.models
import notes.manager
import tag.models


class Note(core.models.AbstractEntityModel):
    objects = notes.manager.NoteManager()

    title = django.db.models.TextField(
        max_length=150,
        verbose_name="название",
        help_text="Максимально 150 символов",
        null=False,
        blank=False,
    )
    text = django.db.models.TextField(
        verbose_name="текст заметки",
        help_text="Запишите сюда текст заметки",
        null=True,
        blank=True,
    )
    tags = django.db.models.ManyToManyField(
        tag.models.Tag,
        verbose_name="теги",
        related_name="note_tags",
        blank=True,
    )

    def __str__(self):
        return self.title


__all__ = ()

advanote/notes/forms.py
import django.forms

import notes.models


class NoteForm(django.forms.ModelForm):
    class Meta:
        model = notes.models.Note
        fields = ["title", "text", "tags"]
        widgets = {
            "title": django.forms.TextInput(
                attrs={"placeholder": "Заголовок"},
            ),
            "text": django.forms.Textarea(
                attrs={"placeholder": "Текст"},
            ),
        }


__all__ = ()

advanote/notes/views.py
import django.contrib.auth.mixins
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
import django.views

import notes.forms
import notes.models


class GetNotes(
    django.contrib.auth.mixins.LoginRequiredMixin,
    django.views.View,
):
    def get(self, request):
        notes_list = notes.models.Note.objects.filter(
            owner=request.user,
        ).values("id", "title")
        return JsonResponse(list(notes_list), safe=False)


class Notes(
    django.contrib.auth.mixins.LoginRequiredMixin,
    django.views.View,
):
    def get(self, request):
        notes_list = notes.models.Note.objects.filter(owner=request.user)
        selected_note = None

        if notes_list:
            selected_note = notes_list[0]

        return render(
            request,
            "notes/hello.html",
            {"selected_note": selected_note, "notes": notes_list},
        )


class AddNote(
    django.contrib.auth.mixins.LoginRequiredMixin,
    django.views.View,
):
    model = notes.models.Note
    form_class = notes.forms.NoteForm
    template_name = "notes/add_note.html"
    success_url = "/notes/"

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {"form": form})

    def post(self, request):
        form = notes.forms.NoteForm(request.POST)
        if form.is_valid():
            note = form.save(commit=False)
            note.owner = request.user
            note.save()
            new_note_id = note.id
            return redirect("notes:edit_note", note_id=new_note_id)
        return render(request, self.template_name, {"form": form})


class EditNote(
    django.contrib.auth.mixins.LoginRequiredMixin,
    django.views.View,
):
    def get(self, request, note_id):
        selected_note = get_object_or_404(notes.models.Note, id=note_id)
        form = notes.forms.NoteForm(instance=selected_note)
        return render(
            request,
            "notes/notes.html",
            {"selected_note": selected_note, "form": form},
        )

    def post(self, request, note_id):
        selected_note = get_object_or_404(notes.models.Note, id=note_id)
        form = notes.forms.NoteForm(request.POST, instance=selected_note)
        if form.is_valid():
            form.save()
            return redirect("notes:notes")
        return render(
            request,
            "notes/notes.html",
            {"selected_note": selected_note, "form": form},
        )


class DeleteNote(
    django.contrib.auth.mixins.LoginRequiredMixin,
    django.views.View,
):
    def delete(self, request, note_id):
        note = get_object_or_404(notes.models.Note, id=note_id)
        note.delete()
        return JsonResponse({"message": "Заметка успешно удалена"})

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


__all__ = ()

advanote/templates/notes/add_note.html
{% load static %}
<form class="modal-form" id="note-form" method="post" action="{% url 'notes:add_note' %}">
    <link href="{% static 'css/tasks-styles.css' %}" rel="stylesheet">
    {% csrf_token %}
    <div class="form-group">
        {{ form.title }}
    </div>
    <div class="form-group note-text">
        {{ form.text }}
    </div>
</form>

advanote/templates/notes/hello.html
<!DOCTYPE html>
<html lang="en">
{% extends "base.html" %}
{% load static %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <title>Заметки</title>
    <link href="{% static 'css/tasks-styles.css' %}" rel="stylesheet">
    <link href="{% static 'css/notes.css' %}" rel="stylesheet">
</head>
<body>

<header>
    <div class="hello-header">
        <p style="font-style: italic; opacity: 0.7; margin-left: 10px;">заметки / </p>
    </div>
</header>
<div class="overlay" id="overlay"></div>
<div class="container">
    <h1 style="font-family: Calibri, sans-serif; font-weight: bold;">Заметки</h1>
    <p style="font-family: Calibri, sans-serif; margin-top: 20px; font-style: italic">Чтобы добавить заметку, нажмите на "+" в меню</p>
    <p style="font-family: Calibri, sans-serif; margin-top: 10px; font-style: italic">Чтобы сохранить новую заметку, нажмите клавишу "Enter" в заголовке всплывающего окна</p>
    <p style="font-family: Calibri, sans-serif; margin-top: 10px; font-style: italic">Для редактирования заметок доступно автосохранение</p>

</div>
<script src="{% static 'js/notes.js' %}"></script>
</body>
</html>
{% endblock %}

advanote/templates/notes/notes.html
<!DOCTYPE html>
<html lang="en">
{% extends "base.html" %}
{% load static %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <title>Заметки</title>
    <link href="{% static 'css/tasks-styles.css' %}" rel="stylesheet">
    <link href="{% static 'css/notes.css' %}" rel="stylesheet">
</head>
<body>

{% if selected_note %}
<header>
    <div class="header-content">
        <p style="font-style: italic; opacity: 0.7; margin-left: 10px;">заметки / {{ selected_note.title }}</p>
        <img src="{% static 'img/delete.png' %}" class="delete-note-icon" alt="Удалить" onclick="deleteNote()">
    </div>
</header>
<div class="overlay" id="overlay"></div>
<div class="container">
    <form id="note-form" method="post" data-note-id="{{ selected_note.id }}">
        {% csrf_token %}
        <div class="form-group">
            <input type="text" placeholder="Заголовок" id="title" name="title" value="{{ selected_note.title }}">
        </div>
        <div class="form-group text-form">
            <textarea id="text" placeholder="Текст" name="text">{{ selected_note.text }}</textarea>
        </div>
    </form>
</div>
{% endif %}
<script src="{% static 'js/notes.js' %}"></script>
</body>
</html>
{% endblock %}