advanote/advanote/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("authorization.urls", namespace="authorization")),
    path("today/", include("today.urls", namespace="today")),
    path("tasks/", include("tasks.urls", namespace="tasks")),
    path("notes/", include("notes.urls", namespace="notes")),
    path("projects/", include("projects.urls", namespace="projects")),
]

advanote/notes/urls.py
from django.urls import path

import notes.views


app_name = "notes"
urlpatterns = [
    path("", notes.views.Notes.as_view(), name="notes"),
    path("add_note/", notes.views.AddNote.as_view(), name="add_note"),
    path("<int:note_id>/", notes.views.EditNote.as_view(), name="edit_note"),
    path(
        "<int:note_id>/delete/",
        notes.views.DeleteNote.as_view(),
        name="delete_note",
    ),
    path("get_notes/", notes.views.GetNotes.as_view(), name="get_notes"),
]

advanote/projects/urls.py
import django.urls

import projects.views

app_name = "projects"
urlpatterns = [
    django.urls.path(
        "create/",
        projects.views.CreateProject.as_view(),
        name="create",
    ),
    django.urls.path(
        "",
        projects.views.ProjectsListPage.as_view(),
        name="page",
    ),
    django.urls.path(
        "edite/<int:project_id>/",
        projects.views.ProjectEditPage.as_view(),
        name="project_edite",
    ),
    django.urls.path(
        "<int:pk>/",
        projects.views.ProjectDetail.as_view(),
        name="project_detail",
    ),
    django.urls.path(
        "createlink/<int:pk>/",
        projects.views.CreateInviteLink.as_view(),
        name="create_invite",
    ),
    django.urls.path(
        "accept_invite/<int:pk>/<str:invite_code>/",
        projects.views.AcceptInvite.as_view(),
        name="invite_link",
    ),
]

advanote/projects/models.py
import django.contrib.auth.models
import django.db.models

import core.models
import notes.models
import projects.manager
import tasks.models


class Project(core.models.AbstractEntityModel):
    objects = projects.manager.ProjectManager()
    name = django.db.models.CharField(
        max_length=150,
        verbose_name="название",
        help_text="Максимально 150 символов",
    )
    description = django.db.models.TextField(
        verbose_name="описание",
        help_text="Введите описание проекта",
        null=True,
        blank=True,
    )
    members = django.db.models.ManyToManyField(
        django.contrib.auth.models.User,
        related_name="members",
        verbose_name="участники проекта",
    )
    task = django.db.models.ManyToManyField(
        tasks.models.Task,
        related_name="tasks",
        verbose_name="задачи",
    )
    note = django.db.models.ManyToManyField(
        notes.models.Note,
        related_name="notes",
        verbose_name="заметки",
    )
    invite_link = django.db.models.CharField(
        max_length=150,
        verbose_name="пригласительная ссылка",
        help_text="Максимально 150 символов",
        null=True,
        blank=True,
    )


__all__ = ()

advanote/projects/forms.py
import django.forms

import notes.models
import projects.models
import tasks.models


class ProjectCreateForm(django.forms.ModelForm):
    task = django.forms.ModelMultipleChoiceField(
        queryset=None,
        widget=django.forms.CheckboxSelectMultiple(),
        required=False,
    )
    note = django.forms.ModelMultipleChoiceField(
        queryset=None,
        widget=django.forms.CheckboxSelectMultiple(),
        required=False,
    )

    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields[
            "task"
        ].queryset = tasks.models.Task.objects.get_user_tasks(
            request.user.id,
        )
        self.fields[
            "note"
        ].queryset = notes.models.Note.objects.get_user_notes(
            request.user.id,
        )

    class Meta:
        model = projects.models.Project
        fields = (
            projects.models.Project.name.field.name,
            projects.models.Project.description.field.name,
            projects.models.Project.task.field.name,
            projects.models.Project.note.field.name,
        )


class ProjectPageEditForm(django.forms.ModelForm):
    task = django.forms.ModelMultipleChoiceField(
        queryset=None,
        widget=django.forms.CheckboxSelectMultiple(),
        required=False,
    )
    note = django.forms.ModelMultipleChoiceField(
        queryset=None,
        widget=django.forms.CheckboxSelectMultiple(),
        required=False,
    )
    members = django.forms.ModelMultipleChoiceField(
        queryset=None,
        widget=django.forms.CheckboxSelectMultiple(),
        required=False,
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["task"].queryset = self.instance.task
        self.fields["note"].queryset = self.instance.note
        self.fields["members"].queryset = self.instance.members

    class Meta:
        model = projects.models.Project
        fields = (
            projects.models.Project.name.field.name,
            projects.models.Project.description.field.name,
            projects.models.Project.members.field.name,
            projects.models.Project.task.field.name,
            projects.models.Project.note.field.name,
        )


__all__ = ()

advanote/projects/views.py
import uuid

import django.contrib.auth.mixins
import django.http
import django.shortcuts
import django.urls
import django.views.generic

import projects.forms
import projects.models


class CreateProject(
    django.contrib.auth.mixins.LoginRequiredMixin,
    django.views.generic.FormView,
):
    form_class = projects.forms.ProjectCreateForm
    success_url = django.urls.reverse_lazy("projects:page")
    template_name = "projects/create.html"

    def get(self, request, *args, **kwargs):
        form = self.form_class(request)
        context = {
            "form": form,
        }
        return django.shortcuts.render(request, self.template_name, context)

    def get_form(self, form_class=None, **kwargs):
        if form_class is None:
            form_class = self.get_form_class()
        params = self.get_form_kwargs()
        params.update(kwargs)
        return form_class(**params)

    def post(self, request, *args, **kwargs):
        form = self.get_form(request=request)
        if form.is_valid():
            return self.form_valid(form, request=request)
        return self.form_invalid(form)

    def form_invalid(self, form):
        return super().form_invalid(form)

    def form_valid(self, form, **kwargs):
        project = form.save(commit=False)
        project.owner = kwargs["request"].user
        project.save()
        form.save_m2m()
        return super().form_valid(form)


class ProjectsListPage(
    django.contrib.auth.mixins.LoginRequiredMixin,
    django.views.generic.ListView,
):
    context_object_name = "projects"
    template_name = "projects/projects_page.html"

    def get_queryset(self):
        return projects.models.Project.objects.get_all_user_projects(
            self.request.user,
        )


class ProjectEditPage(
    django.contrib.auth.mixins.LoginRequiredMixin,
    django.contrib.auth.mixins.UserPassesTestMixin,
    django.views.generic.View,
):
    template_name = "projects/project_edite.html"

    def test_func(self):
        project = projects.models.Project.objects.get_all_members(
            self.kwargs["project_id"],
        )
        if not project.exists():
            return False
        project = project[0]
        if project.owner == self.request.user:
            return True
        if self.request.user in project.members.all():
            return True
        return False

    def post(self, request, *args, **kwargs):
        project = projects.models.Project.objects.get(id=kwargs["project_id"])
        form = projects.forms.ProjectPageEditForm(
            request.POST,
            instance=project,
        )

        if form.is_valid():
            project = form.save(commit=False)
            project.owner = request.user
            project.save()
            form.save_m2m()

        context = {
            "form": form,
            "project": project,
        }
        return django.shortcuts.render(request, self.template_name, context)

    def get(self, request, *args, **kwargs):
        project = projects.models.Project.objects.get(id=kwargs["project_id"])
        form = projects.forms.ProjectPageEditForm(instance=project)
        context = {
            "form": form,
            "project": project,
        }
        return django.shortcuts.render(request, self.template_name, context)


class ProjectDetail(
    django.contrib.auth.mixins.LoginRequiredMixin,
    django.contrib.auth.mixins.UserPassesTestMixin,
    django.views.generic.DetailView,
):
    model = projects.models.Project
    template_name = "projects/project.html"

    def test_func(self):
        project = projects.models.Project.objects.get_all_members(
            self.kwargs["pk"],
        )
        if not project.exists():
            return False
        project = project[0]
        if project.owner == self.request.user:
            return True
        if self.request.user in project.members.all():
            return True
        return False


class AcceptInvite(
    django.contrib.auth.mixins.LoginRequiredMixin,
    django.views.generic.View,
):
    def get(self, request, *args, **kwargs):
        project = django.shortcuts.get_object_or_404(
            projects.models.Project,
            pk=kwargs["pk"],
        )
        if all(
            (
                project.invite_link == kwargs["invite_code"],
                request.user not in project.members.all(),
                request.user != project.owner,
            ),
        ):
            project.members.add(request.user)
            return django.shortcuts.redirect(
                django.urls.reverse(
                    "projects:project_detail",
                    kwargs={"pk": kwargs["pk"]},
                ),
            )
        return django.http.HttpResponse(
            "Ссылка не действительна или вы уже приняли приглашение!",
        )


class CreateInviteLink(
    django.contrib.auth.mixins.LoginRequiredMixin,
    django.views.generic.View,
):
    def get(self, request, *args, **kwargs):
        project = django.shortcuts.get_object_or_404(
            projects.models.Project,
            pk=kwargs["pk"],
        )
        if request.user == project.owner:
            project.invite_link = uuid.uuid4()
            project.save()
        return django.shortcuts.redirect(
            django.urls.reverse(
                "projects:project_detail",
                kwargs={"pk": kwargs["pk"]},
            ),
        )


__all__ = ()

advanote/templates/projects/create.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<head>
    <link href="{% static 'css/tasks-styles.css' %}" rel="stylesheet">
    <link href="{% static 'css/notes.css' %}" rel="stylesheet">
</head>
<div class="container">
<h1>Создание проекта</h1>
<form method="post">
    {% csrf_token %}
    <table class="table table-th-block">
        <tbody>
        <tr>
            <td class="active">Название проекта:</td>
            <td>{{ form.name }}</td>
        </tr>
        <tr>
            <td class="active">Описание проекта:</td>
            <td>{{ form.description }}</td>
        </tr>
        <tr>
            <td class="active">Задачи проекта:</td>
            <td >{{ form.task }}</td>
        </tr>
        <tr>
            <td class="active">Заметки проекта:</td>
            <td class="scroll-bar">{{ form.note }}</td>
        </tr>
        </tbody>
    </table>
    <div class="form-group">
        <button type="submit" class="btn btn-primary btn-block button">Создать</button>
    </div>
    <input type="hidden" name="next" value="{{ next }}">
</form>
</div>
{% endblock %}

advanote/templates/projects/project.html
{% extends "base.html" %}

{% block content %}
{% load static %}
<div class="container">
    <script src="{% static 'js/tasks.js' %}"></script>
    <link href="/static/css/tasks-styles.css" rel="stylesheet">
    <div class="overlay" id="overlay"></div>
    <h1>{{ project.name }}</h1>
    <table class="table table-th-block">
        <tbody>
        <tr>
            <td class="active">Создатель проекта:</td>
            <td>{{ project.owner.username }}</td>
        </tr>
        <tr>
            <td class="active">Описание проекта:</td>
            <td>
                <div class="scroll-block">
                    {{ project.description }}
                </div>
            </td>
        </tr>
        <tr>
            <td class="active">Задачи проекта:</td>
            <td>
                <div class="scroll-block">
                    {% for task in project.task.all %}
                    <div class="task" data-task-id="{{ task.id }}">{{ task.title }}</div>
                    {% endfor %}
                </div>
            </td>
        </tr>
        <tr>
            <td class="active">Заметки проекта:</td>
            <td>
                <div class="scroll-block">
                    {% for note in project.note.all %}
                    <p><a href="">{{ note.title }}</a></p>
                    {% endfor %}
                </div>
            </td>
        </tr>
        <tr>
            <td class="active">Участники проекта:</td>
            <td>
                <div class="scroll-block">
                    {% for member in project.members.all %}
                    <p>{{ member.username }}</p>
                    {% endfor %}
                </div>
            </td>
        </tr>
        {% if project.invite_link and project.owner == user %}
        <tr>
            <td class="active">Пригласительная ссылка:</td>
            <td>{{ request.scheme }}://{{ request.META.HTTP_HOST }}{% url 'projects:invite_link' pk=project.id invite_code=project.invite_link %}</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    {% if project.owner == user %}
    <a href="{% url 'projects:create_invite' project.id %}" class="custom-btn btn-16">{% if project.invite_link %} Новая пригласительная ссылка {% else %} Создать пригласительную ссылку {% endif %}</a>
    {% endif %}
</div>
{% endblock %}

advanote/templates/projects/project_edite.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<head>
    <link href="{% static 'css/tasks-styles.css' %}" rel="stylesheet">
    <link href="{% static 'css/notes.css' %}" rel="stylesheet">
</head>
<div class="container">
    <h1>{{ project.name }}</h1>
    <form method="post">
        {% csrf_token %}
        <table class="table table-th-block">
            <tbody>
            <tr>
                <td class="active">Название проекта:</td>
                <td>{{ form.name }}</td>
            </tr>
            <tr>
                <td class="active">Описание проекта:</td>
                <td>{{ form.description }}</td>
            </tr>
            <tr>
                <td class="active">Задачи проекта:</td>
                <td class="scroll-bar">{{ form.task }}</td>
            </tr>
            <tr>
                <td class="active">Заметки проекта:</td>
                <td class="scroll-bar">{{ form.note }}</td>
            </tr>
            <tr>
                <td class="active">Участники проекта:</td>
                <td class="scroll-bar">{{ form.members }}</td>
            </tr>
            </tbody>
            <p>Создатель: {{ project.owner }}</p>
        </table>
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block button">Сохранить</button>
        </div>
        <input type="hidden" name="next" value="{{ next }}">
    </form>
</div>
{% endblock %}

advanote/templates/projects/projects_page.html
{% extends "base.html" %}

{% block content %}
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Сегодня</title>
    <link href="{% static 'css/tasks-styles.css' %}" rel="stylesheet">
</head>
<div class="tasks">
    <h1>Проекты</h1>
    {% if project_count_process == 0 %}
    <p style="padding: 5px; color: #AEAEAE;">Нет проектов.</p>
    {% else %}
    <p style="padding: 5px; color: #AEAEAE;">Количество проектов: {{ project_count }}</p>
    {% endif %}
    <div class="overlay" id="overlay"></div>
    <div>
        {% for project in projects %}
        <div class="task-container">
            <a href="{% url 'projects:project_detail' project.id %}" class="task">{{ project.name }}</a>
            <a href="{% url 'projects:project_edite' project.id %}">Редактировать</a>
        </div>
        {% endfor %}
    </div>
    <a class="add-task-btn" href="{% url 'projects:create' %}">
        <img src="{% static 'img/add.png' %}" alt="Иконка"> Добавить проект
    </a>
</div>

{% endblock %}