advanote/advanote/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("authorization.urls", namespace="authorization")),
    path("today/", include("today.urls", namespace="today")),
    path("tasks/", include("tasks.urls", namespace="tasks")),
    path("notes/", include("notes.urls", namespace="notes")),
    path("projects/", include("projects.urls", namespace="projects")),
]

advanote/authorization/urls.py
import django.contrib.auth.views
import django.urls

import authorization.views
import users.views

app_name = "authorization"
urlpatterns = [
    django.urls.path(
        "",
        authorization.views.Login.as_view(),
        name="login",
    ),
    django.urls.path(
        "signup/",
        authorization.views.Signup.as_view(),
        name="signup",
    ),
    django.urls.path(
        "emailconfirm/<uidb64>/<token>",
        authorization.views.ConfirmEmail.as_view(),
        name="email_confirm",
    ),
    django.urls.path(
        "password_reset/",
        authorization.views.ResetPassword.as_view(),
        name="password_reset",
    ),
    django.urls.path(
        "password_done/",
        authorization.views.ResetPasswordDone.as_view(),
        name="password_done",
    ),
    django.urls.path(
        "password_confirm/<uidb64>/<token>",
        authorization.views.ResetPasswordConfirm.as_view(),
        name="password_confirm",
    ),
    django.urls.path(
        "password_complete/",
        authorization.views.ResetPasswordComplete.as_view(),
        name="password_complete",
    ),
    django.urls.path(
        "profile/",
        users.views.Profile.as_view(),
        name="profile",
    ),
    django.urls.path(
        "logout/",
        django.contrib.auth.views.LogoutView.as_view(
            template_name="authorization/reset_done.html",
        ),
        name="logout",
    ),
]

advanote/notes/urls.py
from django.urls import path

import notes.views


app_name = "notes"
urlpatterns = [
    path("", notes.views.Notes.as_view(), name="notes"),
    path("add_note/", notes.views.AddNote.as_view(), name="add_note"),
    path("<int:note_id>/", notes.views.EditNote.as_view(), name="edit_note"),
    path(
        "<int:note_id>/delete/",
        notes.views.DeleteNote.as_view(),
        name="delete_note",
    ),
    path("get_notes/", notes.views.GetNotes.as_view(), name="get_notes"),
]

advanote/projects/urls.py
import django.urls

import projects.views

app_name = "projects"
urlpatterns = [
    django.urls.path(
        "create/",
        projects.views.CreateProject.as_view(),
        name="create",
    ),
    django.urls.path(
        "",
        projects.views.ProjectsListPage.as_view(),
        name="page",
    ),
    django.urls.path(
        "edite/<int:project_id>/",
        projects.views.ProjectEditPage.as_view(),
        name="project_edite",
    ),
    django.urls.path(
        "<int:pk>/",
        projects.views.ProjectDetail.as_view(),
        name="project_detail",
    ),
    django.urls.path(
        "createlink/<int:pk>/",
        projects.views.CreateInviteLink.as_view(),
        name="create_invite",
    ),
    django.urls.path(
        "accept_invite/<int:pk>/<str:invite_code>/",
        projects.views.AcceptInvite.as_view(),
        name="invite_link",
    ),
]

advanote/today/urls.py
from django.urls import path
import today.views


app_name = "today"
urlpatterns = [
    path("", today.views.Today.as_view(), name="today"),
]

advanote/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Advanote{% endblock %}</title>
    <link rel="icon" type="image/png" href="{% static 'img/logo.png' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/authorization.css' %}" rel="stylesheet">
    <link href="{% static 'css/menu-styles.css' %}" rel="stylesheet">
    <link href="{% static 'css/notes-styles.css' %}" rel="stylesheet">
    <link href="{% static 'css/notes.css' %}" rel="stylesheet">
</head>

<body>
<div class="menu">
        <div class="button-container">
            <button class="profile-button icon-button {% if request.path == '/profile/' %}active{% endif %}">
                <a href="{% url 'authorization:profile' %}">
                    <img src="{% static 'img/profile.png' %}" alt="Иконка"> {{ user.username }}
                </a>
            </button>
            <button class="icon-button {% if request.path == '/today/' %}active{% endif %}">
                <a href="{% url 'today:today' %}">
                    <img src="{% static 'img/today.png' %}" alt="Иконка"> Сегодня
                    <span class="task-count">{{ tasks_count }}</span>
                </a>
            </button>
            <button class="icon-button {% if request.path == '/notes/' %}active{% endif %}">
                <a href="{% url 'notes:notes' %}">
                    <img src="{% static 'img/notes.png' %}" alt="Иконка"> Заметки
                </a>
                <img src="{% static 'img/plus.png' %}" class="add-note-btn" alt="Добавить заметку">
                <img src="{% static 'img/right-arrow.png' %}" id="rightArrowIcon" class="arrow-icon" alt="Стрелка" onclick="toggleNotesDropdown()">
                <img src="{% static 'img/down-arrow.png' %}" id="downArrowIcon" class="arrow-icon hidden" alt="Стрелка" onclick="toggleNotesDropdown()">
            </button>
            <div class="dropdown-content" id="notesDropdown" style="display: none;"></div>
            <button class="icon-button {% if request.path == '/projects/' %}active{% endif %}">
                <a href="{% url 'projects:page' %}">
                    <img src="{% static 'img/projects.png' %}" alt="Иконка"> Проекты
                </a>
            </button>
        </div>
</div>
<div class="content" style="margin-left: 200px;">
    {% block content %}
    {% endblock %}
</div>
<script src="{% static 'js/notes.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>